version: "3.5"

services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image:
      mrgurgel/postgres_miguilim
    container_name: bd_miguilim
    ports:
    - "5006:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    networks:
    - nw_miguilim

networks:
  nw_miguilim:
    name: miguilin-dspace_nw_miguilim
    driver: bridge