version: "3.5"

services:

  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    image:
      mrgurgel/postgres_miguilim
    container_name: bd_miguilim
    ports:
      - "127.0.0.1:5006:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=America/Sao_Paulo
    volumes:
      - dbdata:/var/lib/postgresql/data
    network_mode: host

  dspace:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    image:
      mrgurgel/dspace_miguilim
    environment:
      - TZ=America/Sao_Paulo
      - CONFIG_FILE=docker.cfg
      - DEV_MODE=true
      - CONTEXT_NAME=miguilim
      - DB_PASSWORD=${DB_PASSWORD}
    container_name: dspace_miguilim
    ports:
    - "80:80"
    tty: true
    volumes:
    - mavenrepo:/root/.m2/repository
    - installfolder:/dspace
    - thirdpardsoftware:/opt
    network_mode: host

volumes:
  mavenrepo:
    name: miguilim-mavenrepo
    driver: local
  installfolder:
    name: miguilim-installfolder
    driver: local
  dbdata:
    name: miguilim-dbdata
    driver: local
  thirdpardsoftware:
    name: miguilim-thirdpardsoftware
    driver: local
