version: "3.5"

services:

  dspace:
    build:
      context: .
      dockerfile: Dockerfile
    image:
      mrgurgel/dspace_miguilim
    environment:
      - TZ=America/Sao_Paulo
      - CONFIG_FILE=docker.cfg
      - DEV_MODE=true
      - CONTEXT_NAME=miguilim
    container_name: dspace_miguilim
    ports:
    - "7006:8080"
    tty: true
    volumes:
    - mavenrepo:/root/.m2/repository
    - installfolder:/dspace
    networks:
      - nw_miguilim

networks:
  nw_miguilim:
    name: miguilin-dspace_nw_miguilim
    driver: bridge

volumes:
  mavenrepo:
    driver: local
  installfolder:
    driver: local
