name: Deploy HMG-Miguilim

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - run: |
          sh docker/dspace/build-dspace.sh